/* // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGvJ8UF2N-OYVRtrU4WpLADNEjuE5266I',
    appId: '1:452769124630:web:1c4a6cfe34c300ac0c0037',
    messagingSenderId: '452769124630',
    projectId: 'visual-journey-eb477',
    authDomain: 'visual-journey-eb477.firebaseapp.com',
    databaseURL: 'https://visual-journey-eb477-default-rtdb.firebaseio.com',
    storageBucket: 'visual-journey-eb477.appspot.com',
    measurementId: 'G-YMS9L2LN4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJx8n4V0c652FviQBn97V3R1gLsEFKZA',
    appId: '1:452769124630:android:bbba917df06f668b0c0037',
    messagingSenderId: '452769124630',
    projectId: 'visual-journey-eb477',
    databaseURL: 'https://visual-journey-eb477-default-rtdb.firebaseio.com',
    storageBucket: 'visual-journey-eb477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_G9T8h8y4KzurBAT_I4uyeZRdQLqVkU',
    appId: '1:452769124630:ios:53d2912737137f4c0c0037',
    messagingSenderId: '452769124630',
    projectId: 'visual-journey-eb477',
    databaseURL: 'https://visual-journey-eb477-default-rtdb.firebaseio.com',
    storageBucket: 'visual-journey-eb477.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV_G9T8h8y4KzurBAT_I4uyeZRdQLqVkU',
    appId: '1:452769124630:ios:53d2912737137f4c0c0037',
    messagingSenderId: '452769124630',
    projectId: 'visual-journey-eb477',
    databaseURL: 'https://visual-journey-eb477-default-rtdb.firebaseio.com',
    storageBucket: 'visual-journey-eb477.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGvJ8UF2N-OYVRtrU4WpLADNEjuE5266I',
    appId: '1:452769124630:web:581625ea75f7e0a70c0037',
    messagingSenderId: '452769124630',
    projectId: 'visual-journey-eb477',
    authDomain: 'visual-journey-eb477.firebaseapp.com',
    databaseURL: 'https://visual-journey-eb477-default-rtdb.firebaseio.com',
    storageBucket: 'visual-journey-eb477.appspot.com',
    measurementId: 'G-G96WEP0RT0',
  );

}
 */