/* // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyq9xVxvG0Ls5wzdamlWwQKOH8u8bYYqA',
    appId: '1:150045401053:web:99f4776e870274a3b8e034',
    messagingSenderId: '150045401053',
    projectId: 'vs-journey',
    authDomain: 'vs-journey.firebaseapp.com',
    storageBucket: 'vs-journey.appspot.com',
    measurementId: 'G-RNMZS78D7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKF4q-iD1GYOgWjxVC0b0rBeH4swCg3bo',
    appId: '1:150045401053:android:894e53e133ddc720b8e034',
    messagingSenderId: '150045401053',
    projectId: 'vs-journey',
    storageBucket: 'vs-journey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15qah5IAx9KkDlucZp45XLhk5qDtXJV0',
    appId: '1:150045401053:ios:3abaf1532b7b2968b8e034',
    messagingSenderId: '150045401053',
    projectId: 'vs-journey',
    storageBucket: 'vs-journey.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA15qah5IAx9KkDlucZp45XLhk5qDtXJV0',
    appId: '1:150045401053:ios:3abaf1532b7b2968b8e034',
    messagingSenderId: '150045401053',
    projectId: 'vs-journey',
    storageBucket: 'vs-journey.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyq9xVxvG0Ls5wzdamlWwQKOH8u8bYYqA',
    appId: '1:150045401053:web:ca7da2fedd627b18b8e034',
    messagingSenderId: '150045401053',
    projectId: 'vs-journey',
    authDomain: 'vs-journey.firebaseapp.com',
    storageBucket: 'vs-journey.appspot.com',
    measurementId: 'G-JJEWMYENVN',
  );
}
 */