// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWtgRwOCEGN4UMTib0KMz4SOHn9n9I7hA',
    appId: '1:390143938833:web:a5a8f9f1b2ec16f96f3cb0',
    messagingSenderId: '390143938833',
    projectId: 'visualjourney-547ab',
    authDomain: 'visualjourney-547ab.firebaseapp.com',
    storageBucket: 'visualjourney-547ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPkkzazoRaA7obNRi8DQmeHq8GcR9wzo',
    appId: '1:390143938833:android:64be81961fa044f76f3cb0',
    messagingSenderId: '390143938833',
    projectId: 'visualjourney-547ab',
    storageBucket: 'visualjourney-547ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHlu2bsfE0gEZcIslhdnrcBDkhvrFpMmk',
    appId: '1:390143938833:ios:14bb07f76ee5cb186f3cb0',
    messagingSenderId: '390143938833',
    projectId: 'visualjourney-547ab',
    storageBucket: 'visualjourney-547ab.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHlu2bsfE0gEZcIslhdnrcBDkhvrFpMmk',
    appId: '1:390143938833:ios:14bb07f76ee5cb186f3cb0',
    messagingSenderId: '390143938833',
    projectId: 'visualjourney-547ab',
    storageBucket: 'visualjourney-547ab.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWtgRwOCEGN4UMTib0KMz4SOHn9n9I7hA',
    appId: '1:390143938833:web:136b664997e64c2d6f3cb0',
    messagingSenderId: '390143938833',
    projectId: 'visualjourney-547ab',
    authDomain: 'visualjourney-547ab.firebaseapp.com',
    storageBucket: 'visualjourney-547ab.appspot.com',
  );
}
